halderdiptam@dl.com/main/default/objects/Time_Lines__c/Time_Lines__c.object-meta.xml
<CustomObject>
    <label>Time Lines</label>
    <nameField>
        <displayFormat>TL - {000000}</displayFormat>
        <label>Time Lines Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

halderdiptam@dl.com/main/default/objects/Time_Lines__c/fields/Run_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Run_Sequence__c</fullName>
    <label>Run Sequence</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

halderdiptam@dl.com/main/default/objects/Time_Lines__c/fields/Time_Warp_Scheduler__c.field-meta.xml
<CustomField>
    <fullName>Time_Warp_Scheduler__c</fullName>
    <label>Time Warp Scheduler</label>
    <referenceTo>Time_Warp_Scheduler__c</referenceTo>
    <relationshipLabel>Time Lines</relationshipLabel>
    <relationshipName>Time_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

halderdiptam@dl.com/main/default/objects/Time_Warp_Scheduler__c/Time_Warp_Scheduler__c.object-meta.xml
<CustomObject>
    <label>Time Warp Scheduler</label>
    <nameField>
        <label>Time Warp Scheduler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Warp Schedulers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

halderdiptam@dl.com/main/default/classes/TimeToExtend.cls
/**
 * @Description : Class to extent by other Batches using this framework to run and scheduele classes
 */
virtual public class TimeToExtend implements Database.Stateful, Database.Batchable<sObject>, Schedulable {
  public List<Time_Lines__c> classesToRun { get; set; }
  public TimeToExtend() {
  }

  /**
   * @Description : Basic Batch Methods which will be overridden by other classes which will be implementing this
   */
  public virtual Database.QueryLocator start(Database.BatchableContext BC) {
    return null;
  }

  public virtual void execute(
    Database.BatchableContext BC,
    List<sObject> scope
  ) {
  }

  public virtual void finish(Database.BatchableContext BC) {
  }

  /**
   * @Description : Basic Execute method of Schedule class which will be overridden by other classes which will be implementing this
   */
  public virtual void execute(System.SchedulableContext sc) {
  }

  /**
   * @Description : Completed to be call by the Finish of the Batch to execute the next Batch
   */
  public virtual void completed(String JOB_NAME, Database.BatchableContext BC) {
    if (this.classesToRun?.isEmpty())
      return;

    Time_Lines__c line = this.classesToRun[0];
    TimeToExtend timerInstance = (TimeToExtend) (Type.forName(
        line.Class_Name__c
      ))
      .newInstance();
    this.classesToRun.remove(this.classesToRun.indexOf(line));
    timerInstance.classesToRun = this.classesToRun;
    Database.executeBatch(timerInstance);
  }

  /**
   * @Description : Completed to be call by the execute of the scheduled class to execute the next Batch
   */
  public virtual void completed(String JOB_NAME, System.SchedulableContext SC) {
    TimeToExtend timerInstance = (TimeToExtend) Type.forName(JOB_NAME)
      .newInstance();

    List<Time_Lines__c> timeWrappers = [
      SELECT id, Class_Name__c, Time_Warp_Scheduler__c
      FROM Time_Lines__c
      WHERE Class_Name__c = :JOB_NAME
      LIMIT 1
    ];

    List<Time_Lines__c> timeLines = [
      SELECT id, Class_Name__c, Time_Warp_Scheduler__c
      FROM Time_Lines__c
      WHERE
        Time_Warp_Scheduler__c = :timeWrappers[0].Time_Warp_Scheduler__c
        AND Class_Name__c != :JOB_NAME
      ORDER BY Run_Sequence__c ASC
    ];

    timerInstance.classesToRun = timeLines;
    Database.executeBatch(timerInstance);
  }
}